# https://quarto.org/docs/projects/quarto-projects.html
project:
  type: website
  output-dir: _site

# https://quarto.org/docs/websites/
website:
  title: Quarto Julia Template
  page-navigation: true
  bread-crumbs: true
  back-to-top-navigation: true
  reader-mode: true
  repo-url: https://github.com/sosiristseng/template-quarto-julia
  site-url: https://sosiristseng.github.io/template-quarto-julia
  search:
    show-item-context: true
    type: overlay
  # https://quarto.org/docs/websites/website-navigation.html
  navbar:
    search: true
    tools:
      - icon: github
        href: https://github.com/sosiristseng/template-quarto-julia
  sidebar:
    title: false
    style: floating
    collapse-level: 2
    align: left
    contents:
      - index.ipynb
      - pythonplot.ipynb
      - pythonplot-lit.ipynb
      - section: "Subdir"
        contents:
          - sub/plots.ipynb
          - sub/plots-lit.ipynb
      - about.qmd


# bibliography: references.bib

# https://quarto.org/docs/output-formats/html-basics.html
format:
  html:
    respect-user-color-scheme: true
    toc: true
    theme: simplex
    code-copy: true
    code-overflow: wrap
    grid:
      sidebar-width: 300px
      body-width: 1000px
      margin-width: 350px
    # keep-md: true
    # css: styles.css
